/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smallproject.passgenmrc;

/**
 *
 * @author Mateus Campos
 */
public class TelaPassGen extends javax.swing.JFrame {

    /**
     * Creates new form TelaPassGen
     */
    public TelaPassGen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldCaractRandom = new javax.swing.JTextField();
        BtnGenPass = new javax.swing.JButton();
        Radio8Caract = new javax.swing.JRadioButton();
        Radio10Caract = new javax.swing.JRadioButton();
        BtnSaveBottom = new javax.swing.JButton();
        BtnCopyBottom = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        BtnCleanSelection = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BtnSaveMenu = new javax.swing.JMenuItem();
        BtnCopyMenu = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Número de caracteres para sua senha:");

        fieldCaractRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCaractRandomActionPerformed(evt);
            }
        });

        BtnGenPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnGenPass.setText("Gerar Senha");
        BtnGenPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenPassActionPerformed(evt);
            }
        });

        Radio8Caract.setText("8 caracteres");
        Radio8Caract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio8CaractActionPerformed(evt);
            }
        });

        Radio10Caract.setText("10 caracteres");
        Radio10Caract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio10CaractActionPerformed(evt);
            }
        });

        BtnSaveBottom.setText("Salvar");
        BtnSaveBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveBottomActionPerformed(evt);
            }
        });

        BtnCopyBottom.setText("Copiar");
        BtnCopyBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCopyBottomActionPerformed(evt);
            }
        });

        BtnExit.setText("Sair");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        BtnCleanSelection.setText("Limpar");
        BtnCleanSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCleanSelectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtnGenPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Radio8Caract)
                        .addGap(30, 30, 30)
                        .addComponent(Radio10Caract)
                        .addGap(45, 45, 45)
                        .addComponent(fieldCaractRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnSaveBottom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnCopyBottom)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCleanSelection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnExit)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Radio8Caract)
                    .addComponent(Radio10Caract)
                    .addComponent(fieldCaractRandom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnGenPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSaveBottom)
                    .addComponent(BtnCopyBottom)
                    .addComponent(BtnExit)
                    .addComponent(BtnCleanSelection))
                .addGap(20, 20, 20))
        );

        jMenu1.setText("File");

        BtnSaveMenu.setText("Salvar");
        BtnSaveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveMenuActionPerformed(evt);
            }
        });
        jMenu1.add(BtnSaveMenu);

        BtnCopyMenu.setText("Copiar");
        BtnCopyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCopyMenuActionPerformed(evt);
            }
        });
        jMenu1.add(BtnCopyMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSaveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSaveMenuActionPerformed

    private void Radio8CaractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio8CaractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio8CaractActionPerformed

    private void Radio10CaractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio10CaractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio10CaractActionPerformed

    private void fieldCaractRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCaractRandomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCaractRandomActionPerformed

    private void BtnGenPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGenPassActionPerformed

    private void BtnCopyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCopyMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCopyMenuActionPerformed

    private void BtnSaveBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveBottomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSaveBottomActionPerformed

    private void BtnCopyBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCopyBottomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCopyBottomActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnCleanSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCleanSelectionActionPerformed
        Radio8Caract.setText("");
        Radio10Caract.setText("");
        fieldCaractRandom.setText("");
    }//GEN-LAST:event_BtnCleanSelectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPassGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPassGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPassGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPassGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPassGen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCleanSelection;
    private javax.swing.JButton BtnCopyBottom;
    private javax.swing.JMenuItem BtnCopyMenu;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnGenPass;
    private javax.swing.JButton BtnSaveBottom;
    private javax.swing.JMenuItem BtnSaveMenu;
    private javax.swing.JRadioButton Radio10Caract;
    private javax.swing.JRadioButton Radio8Caract;
    private javax.swing.JTextField fieldCaractRandom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
